version: '2.4'

services:
    mailhog:
        image: mailhog/mailhog
        ports:
            - 8025:8025

    nginx:
        build: ./docker/nginx
        depends_on:
            - php
        volumes_from:
            - php

    node:
        build: ./docker/node
        command: yarn start
        depends_on:
            - nginx
        volumes_from:
            - php
        ports:
            - 8080:8080

    php:
        build: ./docker/php
        environment:
            DATABASE_URL: "postgresql://thetribe:424242@postgres:5432/thetribe"
            MAILER_URL: smtp://mailhog:1025
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/project

    postgres:
        image: postgres:10.7
        environment:
            PGUSER: thetribe
            PGPASSWORD: 424242
            POSTGRES_USER: thetribe
            POSTGRES_PASSWORD: 424242
